### ISSUE TITLE
Endless rotating circle

### ISSUE THREAD

**Issue by Deepdelver** [hassio-addons/addon-phlex#55]
# Problem/Motivation
After authenticate with the plex authenticator, i'm getting a spinning circle, nothing else responds.
> (Why the issue was filed)
i cannot reach settings or use flextv

## Actual behavior
endless rotating circles

## Steps to reproduce
Install hass, install plugin, login with my account.

Chrome is missing the file https://cdnjs.cloudflare.com/ajax/libs/gridstack.js/src/gridstack.js 
[somesite.notme-1587067630059.log](https://github.com/hassio-addons/addon-phlex/files/4489522/somesite.notme-1587067630059.log)

<blockquote><div><strong><a href="https://cdnjs.cloudflare.com/ajax/libs/gridstack.js/src/gridstack.js">404 Not Found</a></strong></div></blockquote>

**Comment by Deepdelver** [comment]
I thought in this case the log would provide you with enough information. If that isn't the case, then ask what you need and I will provide it.
In this case, I will look in the direction of the 404 of local library you are using from clouflare, this one isn't available anymore.

**Comment by sinclairpaul** [comment]
The addon wraps the application available at https://github.com/d8ahazard/FlexTV

From what I can see an older version is within the addon, probably due to the current issues with the software.

<blockquote><img src="https://avatars0.githubusercontent.com/u/1633844?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/d8ahazard/FlexTV">d8ahazard/FlexTV</a></strong></div><div>Contribute to d8ahazard/FlexTV development by creating an account on GitHub.</div></blockquote>
